spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres?connectionTimeZone=GMT+7
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  activemq:
    broker-url:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


application:
  security:
    jwt:
      secret-key: 790f901d1b963988cb4252177fd343b53362bcba1a82ad618735670ea7b4230b
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
file:
  upload-dir: ${user.dir}/src/main/resources/files/
  server-path: ${user.dir}/src/main/resources/files/